### ISSUE TITLE
Unicode code-point ranges

### ISSUE THREAD

**Issue by tavi-cacina** [foonathan/lexy#22]
Is it possible to specify unicode code-point ranges in a rule? For ex. using the lexy::utf8_encoding can lexy model this?
identifier-head -> U+0100-U+02FF, U+0370-U+167F, U+1681-U+180D, or U+180F-U+1DBF

PS  Awesome library!

**Comment by foonathan** [comment]
This is currently not supported (well, you can do `lit_c<u8"\UXXX"> / ...`, but this would take ages to type and compile). It is definitely on my to-do list as well as supporting the named Unicode categories directly.

**Comment by foonathan** [comment]
I've added a first solution using `dsl::code_point.if_<identifier_head>()` where `identifier_head` is a predicate:

```cpp
struct identifier_head
{
     constexpr bool operator()(lexy::code_point cp) const
     {
            auto value = cp.value();
            return (0x0100 <= value && value <= 0x02FF) || …;
     }
};
```

(The name of the predicate influences the name of the `lexy::expected_char_class` error which is why you cannot use a lambda).

Something more convenient will be added in the future.
