### ISSUE TITLE
Case insensitive keyword/symbol table

### ISSUE THREAD

**Issue by Xottab-DUTY** [foonathan/lexy#44]
Feature request:
Ability to add keywords and symbols within symbol table that will be parsed in case-insensitive way.

**Comment by foonathan** [comment]
What is your use case? Do you need to parse e.g. a programming language with case-insensitive keywords? Do you require non-ASCII case translation?

**Comment by jannikw** [comment]
Hi, I could also make use of case insensitive keywords. My use case is a SQL like query language where capitalization of keywords should not matter: `SELECT`, `select`  and `SEleCt` should all be parsed as the same keyword.

**Comment by Xottab-DUTY** [comment]
Yes, my case is a programming language which has only ASCII keywords. 😊

**Comment by foonathan** [comment]
Would you also be interested in prohibiting case mixing? As in `sElECt`?

**Comment by jannikw** [comment]
In my case, i would like to accept any combination of capitalization. So mixing should be allowed.

**Comment by foonathan** [comment]
Alright, this is what I am thinking. I don't want to give built-in support to case insensitivity to `dsl::keyword`/`dsl::symbol`/`dsl::literal`, as this is unnecessary overhead (extra template parameters, longer type names, etc.) for the vast majority that don't need it. Furthermore, there might be additional rules that require this behavior (e.g. `dsl::code_point.lit`), so it is better to make it externally. Second, case-insensitive comparison is just a general case of normalization, e.g. Unicode normal form aware literal matching might also be cool.

So my idea is something like `dsl::normalize<Fn>(rule)` which parses `rule` on normalized input according to `Fn`. The way this would work is that `dsl::normalize` creates a new reader that passes all input through `Fn`. This is done lazily, only when `rule` requests input. When `rule` has completed, the reader is reset to the original behavior.

That way, a case-insensitive keyword matching would be done via `dsl::normalize<lexy::lower_case>(LEXY_KEYWORD("select", id))`.

Potential issues/problems with that approach that need solving:

*  What is the interface of `Fn`? If it takes and returns `char` (or the code unit in general), this requires that it maintains an internal buffer if it needs to be Unicode-aware. If it takes and returns `lexy::code_point`, this requires a buffer for Unicode normalization transformation, and adds overhead due to the necessary encoding/decoding steps. I'm leaning towards `char`, as this is a more general low-level interface.
* What happens when it is combined with a  rule that reads a partial code point. If `Fn` has buffered code units internally, it can't easily "give them back". Maybe it is okay if the partial code point is discarded when the rule finishes?
* Should it also change the iterator types? If it does, it requires changes to `lexy_ext::report_error` to handle different iterator types within one input. If it doesn't, `dsl::normalize<lexy::lower_case>(dsl::capture(...)))` produces a lexeme that is not lower-cased but reflects the original input. This might be surprising, but I actually like it.
* Should lexy provide Unicode-ware lower-case/upper-case/title-case transformation? I think it should, as they are non-trivial to implement for a user. However, this means adding the casing tables to https://github.com/foonathan/lexy/blob/main/include/lexy/_detail/unicode_database.hpp, which increases the binary size. It is probably best to add them in a separate table and investigate whether they show up in the final binary if they are not referenced.
* Should lexy provide Unicode normalization forms? So you could, for example, parse an `ä` regardless of whether it was written as `ä` or `a` + `add dots on top`. However, unlike capitalization, it is unlikely that a grammar requires only Unicode normalization in some parts of the input, so it is probably easier for the user to do normalize the entire input before.

**Comment by foonathan** [comment]
Case insensitive parsing has now been implemented.

Simply wrap a literal rule into `dsl::ascii::case_folding` (or `dsl::unicode::simple_case_folding`), and it will be parsed case insensitively: https://lexy.foonathan.net/playground/?id=4o3c989h8&mode=tree (compiler explorer needs updating before it compiles online). For symbol tables use `.case_folding(dsl::ascii::case_folding)` etc.

Remember to only use lowercase characters in your keywords though if they're parsed with case folding!

**Comment by Xottab-DUTY** [comment]
@foonathan, sorry for ping, but, man, just thank you!!!!! ❤️

**Comment by foonathan** [comment]
No problem, needed it myself actually :D
